/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NimiqWidget {
    'address': string;
  }
  interface NimiqWidgetAttributes extends StencilHTMLAttributes {
    'address'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NimiqWidget': Components.NimiqWidget;
  }

  interface StencilIntrinsicElements {
    'nimiq-widget': Components.NimiqWidgetAttributes;
  }


  interface HTMLNimiqWidgetElement extends Components.NimiqWidget, HTMLStencilElement {}
  var HTMLNimiqWidgetElement: {
    prototype: HTMLNimiqWidgetElement;
    new (): HTMLNimiqWidgetElement;
  };

  interface HTMLElementTagNameMap {
    'nimiq-widget': HTMLNimiqWidgetElement
  }

  interface ElementTagNameMap {
    'nimiq-widget': HTMLNimiqWidgetElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
