/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NimiqWidget {
    /**
    * Address to which the mining rewards will be paid
    */
    'address': string;
    /**
    * If `true`, will hide the widget once user agrees to terms
    */
    'autoHide': boolean;
    /**
    * If `true`, will open the widget once it is loaded
    */
    'autoOpen': boolean;
    /**
    * Language for the user interface
    */
    'language': any;
    /**
    * Mining pool, has to be in format `<url>:<port>`
    */
    'pool': string;
  }
  interface NimiqWidgetAttributes extends StencilHTMLAttributes {
    /**
    * Address to which the mining rewards will be paid
    */
    'address'?: string;
    /**
    * If `true`, will hide the widget once user agrees to terms
    */
    'autoHide'?: boolean;
    /**
    * If `true`, will open the widget once it is loaded
    */
    'autoOpen'?: boolean;
    /**
    * Language for the user interface
    */
    'language'?: any;
    /**
    * Emitted when widget is loaded, can be used to change parameters with JS
    */
    'onNimiq-widget-ready'?: (event: CustomEvent) => void;
    /**
    * Mining pool, has to be in format `<url>:<port>`
    */
    'pool'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NimiqWidget': Components.NimiqWidget;
  }

  interface StencilIntrinsicElements {
    'nimiq-widget': Components.NimiqWidgetAttributes;
  }


  interface HTMLNimiqWidgetElement extends Components.NimiqWidget, HTMLStencilElement {}
  var HTMLNimiqWidgetElement: {
    prototype: HTMLNimiqWidgetElement;
    new (): HTMLNimiqWidgetElement;
  };

  interface HTMLElementTagNameMap {
    'nimiq-widget': HTMLNimiqWidgetElement
  }

  interface ElementTagNameMap {
    'nimiq-widget': HTMLNimiqWidgetElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
